

def problem2():
    """Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms."""

    flag = True
    a = [1, 2]

    while flag:
        a.append(a[-1] + a[-2])
        answer = [x for x in a if x % 2 == 0]

        if answer[-1] > 4_000_000:
            answer.pop(-1)
            print(sum(answer))
            flag = False


problem2()
